### ISSUE TITLE
Check and update the debian folder or remove it completely

### ISSUE THREAD

**Issue by meyerj** [orocos-toolchain/rtt#121]

**Comment by doudou** [comment]
:+1: on removing

**Comment by smits** [comment]
I also vote for removing.

On Tue, Nov 10, 2015 at 2:21 PM Sylvain Joyeux <notifications@github.com>
wrote:

> [image: :+1:] on removing
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orocos-toolchain/rtt/issues/121#issuecomment-155417384>
> .
>
-- 
Ruben Smits, Roboticist - Founder
+32 479 511 786
Intermodalics - Kapeldreef 60, 3001 Heverlee - BELGIUM
www.intermodalics.eu

**Comment by meyerj** [comment]
Done in the toolchain-2.9 branch of rtt (https://github.com/orocos-toolchain/rtt/commit/77d82a7bb53ae526d186808c598c36ef796b17ee) and ocl (https://github.com/orocos-toolchain/ocl/commit/3e5fc51854d0b6e43b3f8b9f0b4c6ef6c4ada51a), that will be merged into master after the release.
