### ISSUE TITLE
librtt-typekit-gnulinux.so.2.7.0 linking error 

### ISSUE THREAD

**Issue by arainbilal** [orocos-toolchain/rtt#212]
The librtt-typekit-gnulinux.so.2.7.0 fails to link when compiling the toolchain for the raspberrypi. The complete log file is attached.
Not sure why RealTimeTypekitGlobals.cpp keeps complaining when linking the library.  Please note that the linking error only occurs when compiling under yocto project.
[log.txt](https://github.com/orocos-toolchain/rtt/files/925273/log.txt)

Any ideas/help will be greatly appreciated. The problem is that I cannot see why except ld error and not sure why RealTimeTypekitGlobals.cpp.o keeps complaining about 'first defined here..' on linking.

**Comment by roboticists** [comment]
Interestingly when I built using toolchain2.9, it builds fine.
