### ISSUE TITLE
getDataSample() always returns container with zero size

### ISSUE THREAD

**Issue by disRecord** [orocos-toolchain/rtt#231]
Following code does not work as expected in `toolchain-2.9`. 

Component A:
```
vector<double> v(10, 0.0);
out_port.setDataSample(v);
```
Component B:
```
vector<double> v;
in_port.getDataSample(v);
cout << "size = " << v.size(); 
```
Output is "`size = 0`" instead of "`size = 10`". The problem persists if complex data type such as `sensor_msg::JointState` is used instead of vector.

It seems that problem was introduced by one of the latest commits, because year old version of `toolchain-2.9` works fine.

In the attachment is test component for `vector` and  `sensor_msg::JointState` datatypes.
[test_samples.zip](https://github.com/orocos-toolchain/rtt/files/1400085/test_samples.zip)

**Comment by disRecord** [comment]
It seems the reason is [commit:62d5462af](../commit/62d5462afcd7a997e09ca9780dbc666c3999ad1e).

This commit fixed https://github.com/orocos-toolchain/rtt/issues/177 issue. It causes `DataObjectInterface::Get` to not copy data in `NoData` state. But because `data_sample()` also uses `Get()`  ([ChannelDataElement.hpp#L112](../blob/c2e08cfa523af6d1e8e8c5cd6c7872981a531731/rtt/internal/ChannelDataElement.hpp#L112)) it also breaks `getDataSample()` behavior.

**Comment by meyerj** [comment]
Thanks for reporting and for the analysis. I added a patch to #117 and merged it into toolchain-2.9 again:
https://github.com/orocos-toolchain/rtt/pull/117/commits/0853ec0c6e9ac5b9aa229e4ac57534d7bfeeb97b

**Comment by disRecord** [comment]
Thank you for fast response! 

But from my viewpoint it's slightly better to replace `DataObjectInterface:Get(T&, bool, bool)` with analog of [`BufferInterface::data_sample()`](../rtt/blob/ce3328a1970a47d17f0ad2ef0b37735a7c91caaf/rtt/base/BufferInterface.hpp#L142). It will have a more clearer semantics.

Should I close the issue?

**Comment by meyerj** [comment]
> But from my viewpoint it's slightly better to replace DataObjectInterface:Get(T&, bool, bool) with analog of BufferInterface::data_sample(). It will have a more clearer semantics.

I agree and also do not like signatures with lists of boolean arguments. A separate method `T data_sample()` would have required either an almost identical copy of `DataObjectLockFree::Get(...)` or yet another internal method along the lines of `DataObjectLockFree::Get(T&, bool, bool)`. But you convinced me that having a clean and consistent `DataObjectInterface` and `BufferInterface` is of more value and that the additional `Get()` overload is only required in the `DataObjectLockFree` case.

Extra patch added to #117: https://github.com/orocos-toolchain/rtt/pull/117/commits/588987c9f0b1d9ee92679b3049d43fda152e2970

Feel free to close this issue yourself if you think it is solved now.
