### ISSUE TITLE
Outdated debian package

### ISSUE THREAD

**Issue by mahaarbo** [orocos-toolchain/rtt#276]
After running `sudo apt-get install ros-kinetic-rtt`, I encountered the same problem as https://github.com/orocos-toolchain/rtt/issues/225 as I am using zsh. It seems the debian package is over 1 year and 9 months old. 

Are there plans of releasing a new package soon? Or is it better to try building from source to keep up to date?

**Comment by meyerj** [comment]
Should be fixed in `ros-kinetic-rtt` version `2.9.1`, released on May 15, or newer.
I am sorry for the long delay.
