### ISSUE TITLE
clarification on copyright

### ISSUE THREAD

**Issue by doudou** [orocos-toolchain/rtt#290]
I've just seen the copyright related commits.

I always have been working under the assumption that RTT was LGPL, or more specifically that one could use RTT-based components in commercial proprietary software.

What I just read tends to prove me wrong. I am referring to:

> The Orocos RTT library is licensed under the terms of the [GNU General Public License, Version 2]
> 
> As a special exception, you may use this file as part of a free
> software library without restriction. Specifically, ...
> 

What follows "specifically" seems to be describing what I am looking for, but since it only refines the sentence before, it does not seem to be that.

What is the position of Intermodalics on this subject ? Is the current language really what you are looking for ? How do you handle *your* RTT-based projects ?

**Comment by smits** [comment]
Hi @doudou , 

AFIAU the goal has always been to provide RTT under an LGPL-like license to allow royalty free usage in commercial proprietary software.  However the LGPL license text is not well suited for libraries that provide functionality through templated code ( see https://discussion.fsfeurope.narkive.com/51K5UZcD/writing-an-exception-to-lgpl-for-a-c-template-library for similar examples).  That is why @psoetens chose to use GPL + special exception.  The recent commits were fixing some inconsistencies in license usage that were the result of moving code from OCL (which is LGPL) to RTT over the last years.

**Comment by meyerj** [comment]
Additionally it should be note that the LGPL incompatibiliy with template libraries has been resolved in version 3.0 of the license text, which added the following paragraph:

> 3. Object Code Incorporating Material from Library Header Files.
> 
> The object code form of an Application may incorporate material from a header file that is part of the Library. You may convey such object code under terms of your choice, provided that, if the incorporated material is not limited to numerical parameters, data structure layouts and accessors, or small macros, inline functions and templates (ten or fewer lines in length), you do both of the following:
> 
> a) Give prominent notice with each copy of the object code that the Library is used in it and that the Library and its use are covered by this License.
> b) Accompany the object code with a copy of the GNU GPL and this license document.

So nowadays this would probably be the license to choose for RTT and what has been written in threads from before 2007/2008 is not valid anymore. See also [this comment](http://eigen.tuxfamily.org/index.php?title=Licensing_FAQ&oldid=1117#But_doesn.27t_the_LGPL_have_issues_with_code_that_is_in_header_files.2C_and_template_libraries.3F) in the Licensing FAQ of [Eigen](http://eigen.tuxfamily.org/), a prominent example of a pure template library licensed under the LGPLv3.

Unfortunately the RTT license has always been "GPLv2 + linking exception" (to my best knowledge) and it cannot be "upgraded" to LGPLv3 without the consent of all original authors and contributors.

**Comment by doudou** [comment]
Thanks for the clarification. This is what I remembered, but I found the text a little bit ambiguous ... wanted to be sure.

I think we can close this now ;-)
