### ISSUE TITLE
 make test has 1/45 failed test

### ISSUE THREAD

**Issue by lepalom** [orocos-toolchain/rtt#89]
Hi,

compiling and testing orocos-rtt on a debian jessie box, I have found that 
     Start  7: corba-ipc-test
 7/45 Test  #7: corba-ipc-test ...................***Failed    0.06 sec

failed.

Where can I obtain a log file?
What should I have to check to find the fail?

**Comment by smits** [comment]
I've seen this before, you can run the test with ORO_LOGLEVEL=7 to get debug output if you'd like. I have the tendency to ignore that particular test ;)

**Comment by lepalom** [comment]
I have run:
ORO_LOGLEVEL=7 make test

but I have found no more information.

Then I have gone to build/tests and then I have done:
ORO_LOGLEVEL=7 ./corba-ipc-test 

the orocos.log is attachhed
0.000 [ Info   ][Logger] Successfully extracted environment variable ORO_LOGLEVEL
0.000 [ Info   ][Logger]  OROCOS version '2.8.0' compiled with GCC 4.9.2. Running in GNU/Linux.
0.000 [ Info   ][Logger] Orocos Logging Activated at level : [ Debug  ] ( 6 ) 
0.000 [ Info   ][Logger] Reference System Time is : 1427186586352069261 ticks ( 1.42719e+09 seconds ).
0.000 [ Info   ][Logger] Logging is relative to this time.
0.000 [ Debug  ][Logger] MainThread started.
0.000 [ Debug  ][Logger] Starting StartStopManager.
0.000 [ Info   ][Logger] RTT_COMPONENT_PATH was set to: ../rtt . Searching in: ../rtt:/usr/local/lib/orocos
0.000 [ Debug  ][Logger] PluginLoader Created
0.000 [ Info   ][Logger] plugin 'rtt' not loaded before.
0.001 [ Info   ][Logger] Loading plugin libraries from directory ../rtt/./plugins ...
0.008 [ Debug  ][Logger] Scanning file ../rtt/./plugins/librtt-scripting-gnulinux.so ...Found library librtt-scripting-gnulinux.so
0.008 [ Info   ][Logger] Loaded RTT Service 'scripting' from 'rtt-scripting'
0.010 [ Debug  ][Logger] Scanning file ../rtt/./plugins/librtt-marshalling-gnulinux.so ...Found library librtt-marshalling-gnulinux.so
0.010 [ Info   ][Logger] Loaded RTT Service 'marshalling' from 'rtt-marshalling'
0.010 [ Info   ][Logger] typekit 'rtt' not loaded before.
0.010 [ Info   ][Logger] Loading typekit libraries from directory ../rtt/./types ...
0.023 [ Debug  ][Logger] Scanning file ../rtt/./types/librtt-typekit-gnulinux.so ...Found library librtt-typekit-gnulinux.so
0.023 [ Info   ][TypekitRepository::Import] Loading Typekit rtt-types.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'int' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'uint' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'double' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'float' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'char' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'bool' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'void' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'FlowStatus' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'SendStatus' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'PropertyBag' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'ConnPolicy' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'SendHandle' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'TaskContext' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'string' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'array' to the Orocos Type System.
0.023 [ Debug  ][TypekitRepository::Import] Registered Type 'rt_string' to the Orocos Type System.
0.023 [ Info   ][Logger] Loaded RTT TypeKit/Transport 'rtt-types' from 'rtt-typekit'
0.025 [ Debug  ][Logger] Scanning file ../rtt/./types/librtt-transport-corba-gnulinux.so ...Found library librtt-transport-corba-gnulinux.so
0.025 [ Info   ][TypekitRepository::Import] Loading Transport CORBA://rtt-types.
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for ConnPolicy
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for TaskContext
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for array
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for bool
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for char
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for double
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for float
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for int
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for rt_string
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for string
0.025 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for uint
0.026 [ Info   ][TypekitRepository::Import] Registered new 'CORBA' transport for void
0.026 [ Info   ][Logger] Loaded RTT TypeKit/Transport 'rtt-corba-types' from 'rtt-transport-corba'
0.026 [ Debug  ][Logger] Scanning file ../rtt/./types/CTestTestfile.cmake ...not a .so library: ignored.
0.026 [ Debug  ][Logger] Scanning file ../rtt/./types/librtt-transport-mqueue-gnulinux.so ...Found library librtt-transport-mqueue-gnulinux.so
0.026 [ Info   ][TypekitRepository::Import] Loading Transport mqueue://rtt-types.
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for array
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for bool
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for char
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for double
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for float
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for int
0.027 [ Info   ][TypekitRepository::Import] Registered new 'mqueue' transport for uint
0.027 [ Debug  ][TypekitRepository::Import] Transport mqueue did not install a fallback handler for 'unknown_t'.
0.027 [ Info   ][Logger] Loaded RTT TypeKit/Transport 'rtt-mqueue-transport' from 'rtt-transport-mqueue'
0.027 [ Debug  ][Logger] Scanning file ../rtt/./types/Makefile ...not a .so library: ignored.
0.027 [ Debug  ][Logger] Scanning file ../rtt/./types/CMakeFiles ...not a regular file: ignored.
0.027 [ Debug  ][Logger] Scanning file ../rtt/./types/cmake_install.cmake ...not a .so library: ignored.
0.027 [ Info   ][Logger] RTT_COMPONENT_PATH was set to: ../rtt . Searching in: ../rtt:/usr/local/lib/orocos
0.028 [ Info   ][ThreadOrb] Starting Orb in a thread.
0.028 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_RT, priority=1, CPU affinity=0, with name='Activity'
0.028 [ Warning][Thread] Lowering scheduler type to SCHED_OTHER for non-privileged users..
0.028 [ Debug  ][Thread] Setting CPU affinity to 0
0.028 [ Warning][Activity] Lowering scheduler type to SCHED_OTHER for non-privileged users..
0.028 [ Info   ][Activity] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11877 ).
0.028 [ Info   ][Logger] LogLevel unaltered by test-runner.
0.028 [ Info   ][OrbRunner] Entering orb->run().
0.028 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.029 [ Debug  ][Thread] Setting CPU affinity to 0
0.029 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11878 ).
0.029 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.029 [ Debug  ][Thread] Setting CPU affinity to 0
0.029 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11879 ).
0.029 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.029 [ Debug  ][Thread] Setting CPU affinity to 0
0.029 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11880 ).
0.029 [ Debug  ][~Thread] Terminating NotFound
0.030 [ Debug  ][Thread]  done
0.030 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.030 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.030 [ ERROR  ][TaskContextProxy] NotFound
0.030 [ Debug  ][~Thread] Terminating root
0.031 [ Debug  ][Thread]  done
0.031 [ Debug  ][~Thread] Terminating CorbaTest
0.031 [ Debug  ][Thread]  done
0.031 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.031 [ Debug  ][Thread] Setting CPU affinity to 0
0.031 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11883 ).
0.031 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.031 [ Debug  ][Thread] Setting CPU affinity to 0
0.031 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11884 ).
0.031 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.031 [ Debug  ][Thread] Setting CPU affinity to 0
0.031 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11885 ).
0.031 [ Debug  ][~Thread] Terminating NotFound
0.032 [ Debug  ][Thread]  done
0.032 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.032 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.032 [ ERROR  ][TaskContextProxy] NotFound
0.032 [ Debug  ][~Thread] Terminating root
0.032 [ Debug  ][Thread]  done
0.032 [ Debug  ][~Thread] Terminating CorbaTest
0.032 [ Debug  ][Thread]  done
0.032 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.032 [ Debug  ][Thread] Setting CPU affinity to 0
0.032 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11886 ).
0.032 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.032 [ Debug  ][Thread] Setting CPU affinity to 0
0.032 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11887 ).
0.033 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.033 [ Debug  ][Thread] Setting CPU affinity to 0
0.033 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11888 ).
0.033 [ Debug  ][~Thread] Terminating NotFound
0.033 [ Debug  ][Thread]  done
0.033 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.033 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.033 [ ERROR  ][TaskContextProxy] NotFound
0.033 [ Debug  ][~Thread] Terminating root
0.033 [ Debug  ][Thread]  done
0.033 [ Debug  ][~Thread] Terminating CorbaTest
0.033 [ Debug  ][Thread]  done
0.033 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.034 [ Debug  ][Thread] Setting CPU affinity to 0
0.034 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11889 ).
0.034 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.034 [ Debug  ][Thread] Setting CPU affinity to 0
0.034 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11890 ).
0.034 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.034 [ Debug  ][Thread] Setting CPU affinity to 0
0.034 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11891 ).
0.034 [ Debug  ][~Thread] Terminating NotFound
0.034 [ Debug  ][Thread]  done
0.034 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.034 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.034 [ ERROR  ][TaskContextProxy] NotFound
0.034 [ Debug  ][~Thread] Terminating root
0.035 [ Debug  ][Thread]  done
0.035 [ Debug  ][~Thread] Terminating CorbaTest
0.035 [ Debug  ][Thread]  done
0.035 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.035 [ Debug  ][Thread] Setting CPU affinity to 0
0.035 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11892 ).
0.035 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.035 [ Debug  ][Thread] Setting CPU affinity to 0
0.035 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11893 ).
0.035 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.035 [ Debug  ][Thread] Setting CPU affinity to 0
0.035 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11894 ).
0.035 [ Debug  ][~Thread] Terminating NotFound
0.035 [ Debug  ][Thread]  done
0.035 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.036 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.036 [ ERROR  ][TaskContextProxy] NotFound
0.036 [ Debug  ][~Thread] Terminating root
0.036 [ Debug  ][Thread]  done
0.036 [ Debug  ][~Thread] Terminating CorbaTest
0.036 [ Debug  ][Thread]  done
0.036 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.036 [ Debug  ][Thread] Setting CPU affinity to 0
0.036 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11895 ).
0.036 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.037 [ Debug  ][Thread] Setting CPU affinity to 0
0.037 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11896 ).
0.037 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.037 [ Debug  ][Thread] Setting CPU affinity to 0
0.037 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11897 ).
0.037 [ Debug  ][~Thread] Terminating NotFound
0.037 [ Debug  ][Thread]  done
0.037 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.038 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.038 [ ERROR  ][TaskContextProxy] NotFound
0.038 [ Debug  ][~Thread] Terminating root
0.038 [ Debug  ][Thread]  done
0.038 [ Debug  ][~Thread] Terminating CorbaTest
0.038 [ Debug  ][Thread]  done
0.038 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.038 [ Debug  ][Thread] Setting CPU affinity to 0
0.038 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11898 ).
0.038 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.038 [ Debug  ][Thread] Setting CPU affinity to 0
0.039 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11899 ).
0.039 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.039 [ Debug  ][Thread] Setting CPU affinity to 0
0.039 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11900 ).
0.039 [ Debug  ][~Thread] Terminating NotFound
0.039 [ Debug  ][Thread]  done
0.039 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.039 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.039 [ ERROR  ][TaskContextProxy] NotFound
0.040 [ Debug  ][~Thread] Terminating root
0.040 [ Debug  ][Thread]  done
0.040 [ Debug  ][~Thread] Terminating CorbaTest
0.040 [ Debug  ][Thread]  done
0.040 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.040 [ Debug  ][Thread] Setting CPU affinity to 0
0.040 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11901 ).
0.040 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.040 [ Debug  ][Thread] Setting CPU affinity to 0
0.040 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11902 ).
0.040 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.040 [ Debug  ][Thread] Setting CPU affinity to 0
0.041 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11903 ).
0.041 [ Debug  ][~Thread] Terminating NotFound
0.041 [ Debug  ][Thread]  done
0.041 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.041 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.041 [ ERROR  ][TaskContextProxy] NotFound
0.041 [ Debug  ][~Thread] Terminating root
0.041 [ Debug  ][Thread]  done
0.041 [ Debug  ][~Thread] Terminating CorbaTest
0.041 [ Debug  ][Thread]  done
0.042 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='CorbaTest'
0.042 [ Debug  ][Thread] Setting CPU affinity to 0
0.042 [ Info   ][CorbaTest] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11904 ).
0.042 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='root'
0.042 [ Debug  ][Thread] Setting CPU affinity to 0
0.042 [ Info   ][root] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11905 ).
0.042 [ Info   ][Thread] Creating Thread for scheduler=ORO_SCHED_OTHER, priority=1, CPU affinity=0, with name='NotFound'
0.042 [ Debug  ][Thread] Setting CPU affinity to 0
0.042 [ Info   ][NotFound] Thread created with scheduler type 'ORO_SCHED_OTHER', priority 0, cpu affinity 255 and period 0 (PID= 11906 ).
0.042 [ Debug  ][~Thread] Terminating NotFound
0.042 [ Debug  ][Thread]  done
0.042 [ Debug  ][TaskContextProxy] TaskContextProxy found CORBA NameService.
0.043 [ ERROR  ][TaskContextProxy] CORBA exception raised when resolving Object !
0.043 [ ERROR  ][TaskContextProxy] NotFound
0.043 [ Debug  ][~Thread] Terminating root
0.043 [ Debug  ][Thread]  done
0.043 [ Debug  ][~Thread] Terminating CorbaTest
0.043 [ Debug  ][Thread]  done
0.043 [ Info   ][ShutdownOrb] Cleaning up TaskContextServers...
0.043 [ Info   ][ShutdownOrb] Cleanup done.
0.043 [ Info   ][ShutdownOrb] Orb Shutdown...waiting...
0.043 [ Info   ][ShutdownOrb] done.
0.043 [ Info   ][DestroyOrb] Breaking out of orb->run().
0.043 [ Info   ][OrbRunner] Safely stopped.
0.043 [ Debug  ][~Thread] Terminating Activity
0.043 [ Debug  ][Thread]  done
0.044 [ Info   ][Logger] Orb destroyed.
0.044 [ Debug  ][OrbRunner] Stopping StartStopManager.
0.044 [ Debug  ][OrbRunner] PluginLoader Destroyed
0.044 [ Debug  ][OrbRunner] Stopping MainThread.
0.044 [ Info   ][OrbRunner] Orocos Logging Deactivated.

**Comment by meyerj** [comment]
Related PR: #112

**Comment by meyerj** [comment]
Fixed in #112.
